name: Publish to NPM Registry
on:
  push:
    branches: [ main ] # 当主分支有新提交时触发
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Node.js environment
        uses: actions/setup-node@v1
        with:
          node-version: '14'
          
      - name: Install dependencies
        run: npm install
        
      - name: Build package
        run: npm run build
        
      - name: Login to NPM registry
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # 设置 NPM token 密钥
        run: echo "//registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN" > .npmrc
        
      - name: Publish package
        run: npm publish --access public
